# Generated by Django 4.2.17 on 2025-01-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Краткое название лаборатории (аббревиатура)",
                        max_length=100,
                        verbose_name="Аббревиатура",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Полное название лаборатории",
                        max_length=255,
                        verbose_name="Полное название",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название или аббревиатура подразделения",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Полное название подразделения (необязательно)",
                        max_length=255,
                        null=True,
                        verbose_name="Полное название",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("white", "Белая карточка"),
                            ("blue", "Синяя карточка"),
                        ],
                        help_text="Выберите тип отображения карточки",
                        max_length=5,
                        verbose_name="Тип карточки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        help_text="Лаборатория, к которой относится подразделение",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="formulas.laboratory",
                        verbose_name="Лаборатория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ["laboratory", "name"],
                "unique_together": {("laboratory", "name")},
            },
        ),
    ]
