# Generated by Django 4.2.17 on 2025-01-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="card_type",
        ),
        migrations.RemoveField(
            model_name="department",
            name="full_name",
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Название подразделения",
                max_length=100,
                verbose_name="Название",
            ),
        ),
    ]
