# Generated by Django 4.2.16 on 2025-04-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exceltemplate",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Подразделение, к которому привязан шаблон",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excel_templates",
                to="formulas.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.AddField(
            model_name="exceltemplate",
            name="laboratory",
            field=models.ForeignKey(
                default=2,
                help_text="Лаборатория, к которой привязан шаблон",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excel_templates",
                to="formulas.laboratory",
                verbose_name="Лаборатория",
            ),
        ),
    ]
