# Generated by Django 4.2.16 on 2025-04-22 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0002_exceltemplate_department_exceltemplate_laboratory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exceltemplate",
            name="laboratory",
            field=models.ForeignKey(
                help_text="Лаборатория, к которой привязан шаблон",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excel_templates",
                to="formulas.laboratory",
                verbose_name="Лаборатория",
            ),
        ),
    ]
