# Generated by Django 4.2.17 on 2025-01-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0002_remove_department_card_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ("laboratory", "order", "name"),
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "ordering": ("name",),
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Порядок отображения подразделения",
                verbose_name="Порядок",
            ),
        ),
    ]
