# Generated by Django 4.2.17 on 2025-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0003_alter_department_options_alter_laboratory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
            },
        ),
        migrations.AddField(
            model_name="laboratory",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Порядок отображения лаборатории",
                verbose_name="Порядок",
            ),
        ),
    ]
