# Generated by Django 4.2.17 on 2025-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0004_alter_laboratory_options_laboratory_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ("laboratory", "name"),
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
            },
        ),
        migrations.AlterModelOptions(
            name="laboratory",
            options={
                "ordering": ("name",),
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
            },
        ),
        migrations.RemoveField(
            model_name="department",
            name="order",
        ),
        migrations.RemoveField(
            model_name="laboratory",
            name="order",
        ),
    ]
