# Generated by Django 4.2.17 on 2025-01-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0005_alter_department_options_alter_laboratory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Краткое название лаборатории (аббревиатура)",
                max_length=100,
                verbose_name="Аббревиатура",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["laboratory", "name"], name="formulas_de_laborat_547473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(fields=["name"], name="formulas_la_name_7665bd_idx"),
        ),
    ]
