# Generated by Django 4.2.17 on 2025-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0006_alter_laboratory_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалено"),
        ),
    ]
