# Generated by Django 4.2.17 on 2025-01-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0007_department_is_deleted_laboratory_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddField(
            model_name="laboratory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_deleted"], name="formulas_de_is_dele_f35a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(
                fields=["is_deleted"], name="formulas_la_is_dele_0e6f65_idx"
            ),
        ),
    ]
