# Generated by Django 4.2.17 on 2025-01-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0009_alter_department_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
        migrations.AlterField(
            model_name="laboratory",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата удаления"
            ),
        ),
    ]
