# Generated by Django 4.2.17 on 2025-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas", "0010_alter_department_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="department",
            name="formulas_de_laborat_547473_idx",
        ),
        migrations.RemoveIndex(
            model_name="department",
            name="formulas_de_is_dele_f35a15_idx",
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["laboratory", "name", "is_deleted"],
                name="formulas_de_laborat_a100fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["created_at"], name="formulas_de_created_651176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["updated_at"], name="formulas_de_updated_47fce4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(
                fields=["created_at"], name="formulas_la_created_08eb96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laboratory",
            index=models.Index(
                fields=["updated_at"], name="formulas_la_updated_aeb221_idx"
            ),
        ),
    ]
